# Generated by Django 4.1.7 on 2023-03-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_1", models.CharField(max_length=100)),
                ("img_1", models.ImageField(upload_to="pics")),
                ("desc_1", models.TextField()),
            ],
        ),
    ]
